name: sample-deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Check out Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run cake
        shell : bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          dotnet new tool-manifest
          dotnet tool install Cake.Tool
          dotnet tool restore
          dotnet cake ./build.cake 
      - name: Publish generated Blazor webassembly to Netlify
        uses: netlify/actions/cli@master 
        env: 
            NETLIFY_API_KEY: ${{ secrets.NETLIFY_API_KEY }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
            args: deploy --dir=.publish/wwwroot --prod 
           
          